"""add cascade delete for users

Revision ID: 0016
Revises: 0015
Create Date: 2026-06-20 06:03:16.331786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, Sequence[str], None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('fk_chat_messages_room_id'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users_data', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'chat_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_rooms_user_id_fkey'), 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'chat_rooms', 'users_data', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_favorites_user_type'), table_name='favorites')
    op.drop_index(op.f('games_title_trgm'), table_name='games', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('movies_title_trgm'), table_name='movies', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users_data', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users_data', ['user_id'], ['id'])
    op.create_index(op.f('movies_title_trgm'), 'movies', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('games_title_trgm'), 'games', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_favorites_user_type'), 'favorites', ['user_id', 'entity_type'], unique=False)
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('chat_rooms_user_id_fkey'), 'chat_rooms', 'users_data', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chat_messages_room_id'), 'chat_messages', 'chat_rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users_data', ['user_id'], ['id'])
    # ### end Alembic commands ###
