"""add cascade delete for games

Revision ID: 0017
Revises: 0016
Create Date: 2026-06-20 06:09:27.032171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('games_added_by_fkey'), 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users_data', ['added_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('photos_uploaded_by_fkey'), 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users_data', ['uploaded_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key(op.f('photos_uploaded_by_fkey'), 'photos', 'users_data', ['uploaded_by'], ['id'])
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key(op.f('games_added_by_fkey'), 'games', 'users_data', ['added_by'], ['id'])
    # ### end Alembic commands ###
